### ISSUE TITLE
MFT 29: System transfers an amount less than what the user entered

### ISSUE THREAD

**Issue by kkcmah** [enochtsang/seng437-assignment1#4] opened 2016-01-24 21:21 UTC
Function Being Tested: Transfer

------------

Build Number: Version Number 1.0

Reported On: 24/01/16

Description:
The system transfers and prints an incorrect receipt showing a transfer amount $0.50 less than the amount entered. The transfer from and to accounts are switched on the receipt. 

Steps To Reproduce:
1) Run ATM system version 1.0
2) Turn the system on by pressing the "ON" button
3) Enter 10 for the the number of $20 bills 
4) Click “Click to insert card”
5) Input 1 as the card number
6) Input 42 as the PIN number and click “ENTER”
7) Press 3 to choose the “Transfer” option
8) Press 1 to transfer from checking account
9) Press 2 to transfer to savings account
10) Enter 40.00 and press "ENTER"

------------

Expected result:
System prints a correct receipt showing amount and correct updated balance; System records transaction correctly in the log (showing both message to the bank and approval back)

**Comment by bryson189** [comment] 2016-01-25 06:50
Reopened: Defect should be changed to minor. Transfer accounts are still switched on receipt but the transaction completes successfully.

**Comment by enochtsang** [comment] 2016-01-27 20:47
Duplicate of issue #11

**Closed by enochtsang** 2016-01-27 20:47 UTC
Labels: bug, duplicate, Priority - High, Reopened, Severity - High
