### ISSUE TITLE
MFT 22: System deposits an amount less than what the user entered

### ISSUE THREAD

**Issue by kkcmah** [enochtsang/seng437-assignment1#3] opened 2016-01-24 20:55 UTC
Function Being Tested: Deposit

------------
Build Number: Version Number 1.0

Reported On: 24/01/16

Description:
The system deposits an amount less than what was entered. The receipt shows a total balance less than the expected balance.

Steps To Reproduce:
1) Run ATM system version 1.0
2) Turn the system on by pressing the "ON" button
3) Enter 10 for the the number of $20 bills 
4) Click “Click to insert card”
5) Input 1 as the card number
6) Input 42 as the PIN number and click “ENTER”
7) Press 2 to choose the “Deposit” option
8) Press 1 to choose “Checking” account
9) Enter 50.00 and click "ENTER"
10) Click the "Click to insert envelope button"

------------
Expected result:
System accepts envelope; System prints a correct receipt showing amount and correct updated balance; System records transaction correctly in the log (showing message to the bank, approval back, and acceptance)

**Comment by bryson189** [comment] 2016-01-25 06:44
Reopened: Defect still exists in version 1.1. Total balance is $0.10 less than expected balance

**Comment by enochtsang** [comment] 2016-01-27 20:47
Duplicate of issue #7

**Closed by enochtsang** 2016-01-27 20:48 UTC
Labels: bug, duplicate, Priority - High, Reopened, Severity - High
